---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "thanos-compact.fullname" . }}
  labels:
    {{- include "thanos-compact.labels" . | nindent 4 }}
{{- with .Values.http.service.labels }}{{ toYaml . | nindent 4 }}{{ end }}
  {{- with .Values.http.service.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: {{ .Values.http.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "thanos-compact.selectorLabels" . | nindent 4 }}
{{- with .Values.http.service.matchLabels }}{{ toYaml . | nindent 4 }}{{ end }}
