apiVersion: v1
kind: ConfigMap
metadata:
  name: query-frontend-config
  labels:
    {{- include "thanos-query-frontend.labels" . | nindent 4 }}
data:
  cache-config.yaml: |
{{- with .Values.responseCacheConfig }}{{ toYaml . | nindent 4 }}{{ end }}
