---
{{- if .Values.http.ingress.enabled -}}
{{- $fullName := include "thanos-query-frontend.fullname" . -}}
{{- $svcPort := .Values.http.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-http
  labels:
    {{- include "thanos-query-frontend.labels" . | nindent 4 }}
{{- with .Values.http.ingress.labels }}{{ toYaml . | nindent 4 }}{{ end }}
  {{- with .Values.http.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.http.ingress.tls }}
  tls:
    {{- range .Values.http.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.http.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}-http
              servicePort: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- end }}
