---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "thanos-query-frontend.fullname" . }}
  labels:
    {{- include "thanos-query-frontend.labels" . | nindent 4 }}
{{- with .Values.http.service.labels }}{{ toYaml . | nindent 4 }}{{ end }}
  {{- with .Values.http.service.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.http.service.type }}
  {{- if .Values.http.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.http.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.http.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "thanos-query-frontend.selectorLabels" . | nindent 4 }}
{{- with .Values.http.service.matchLabels }}{{ toYaml . | nindent 4 }}{{ end }}
