{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thanos-query-frontend.serviceAccountName" . }}
  labels:
    {{- include "thanos-query-frontend.labels" . | nindent 4 }}
{{- with .Values.serviceAccount.labels }}{{ toYaml . | nindent 4 }}{{ end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
