apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thanos-query.fullname" . }}
  labels:
    {{- include "thanos-query.labels" . | nindent 4 }}
{{- with .Values.deploymentLabels }}{{ toYaml . | nindent 4 }}{{ end }}
  {{- with .Values.deploymentAnnotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount | default 1 }}
{{- end }}
{{- with .Values.strategy }}
  strategy: {{ toYaml . | nindent 4 }}
{{- end }}
  selector:
    matchLabels:
      {{- include "thanos-query.selectorLabels" . | nindent 6 }}
      {{- with .Values.deploymentMatchLabels }}{{ toYaml . | nindent }}{{ end }}
  template:
    metadata:
      labels:
        {{- include "thanos-query.selectorLabels" . | nindent 8 }}
{{- with .Values.podLabels }}{{ toYaml . | nindent 8 }}{{ end }}
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "thanos-query.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.extraEnv }}
          env: {{ toYaml . | nindent 12 }}
          {{- end }}
          args:
            - "query"
            - "--log.level={{ .Values.logLevel }}"
            - "--log.format={{ .Values.logFormat }}"
            - "--http-address=0.0.0.0:{{ .Values.http.port }}"
            - "--grpc-address=0.0.0.0:{{ .Values.grpc.port }}"
            {{- if .Values.tracingConfig }}
            - |
              --tracing.config=
            {{- toYaml .Values.tracingConfig | nindent 14 }}
            {{- end }}
            {{- range .Values.replicaLabels }}
            - "--query.replica-label={{ . }}"
            {{- end }}
            {{- range .Values.selectorLabels }}
            - "--selector-label={{ . }}"
            {{- end }}
            {{- range .Values.stores }}
            - "--store={{ . }}"
            {{- end }}
            {{- if .Values.autoDownsampling }}
            - "--query.auto-downsampling"
            {{- end }}
            {{- if .Values.partialResponse }}
            - "--query.partial-response"
            {{- else }}
            - "--no-query.partial-response"
            {{- end }}
            {{- with .Values.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.http.port }}
            - name: grpc
              containerPort: {{ .Values.grpc.port }}
          livenessProbe:
            failureThreshold: 4
            httpGet:
              path: /-/healthy
              port: http
              scheme: HTTP
            periodSeconds: 30
          readinessProbe:
            failureThreshold: 20 
            httpGet:
              path: /-/ready
              port: http
              scheme: HTTP
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          terminationMessagePolicy: FallbackToLogsOnError
      terminationGracePeriodSeconds: 120
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
