{{- if .Values.httpIngress.enabled -}}
{{- $fullName := include "thanos-query.fullname" . -}}
{{- $svcPort := .Values.service.port.http -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-http
  labels:
    {{- include "thanos-query.labels" . | nindent 4 }}
{{- with .Values.httpIngress.labels }}{{ toYaml . | nindent 4 }}{{ end }}
  {{- with .Values.httpIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.httpIngress.tls }}
  tls:
    {{- range .Values.httpIngress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.httpIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}-http
              servicePort: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- end }}

---

{{- if .Values.grpcIngress.enabled -}}
{{- $fullName := include "thanos-query.fullname" . -}}
{{- $svcPort := .Values.service.port.grpc -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-grpc
  labels:
    {{- include "thanos-query.labels" . | nindent 4 }}
{{- with .Values.grpcIngress.labels }}{{ toYaml . | nindent 4 }}{{ end }}
  {{- with .Values.grpcIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.grpcIngress.tls }}
  tls:
    {{- range .Values.grpcIngress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.grpcIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}-grpc
              servicePort: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- end }}
